# -*- coding: utf-8 -*-
"""ConcatenateBibText.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T2zjOt43RM8XnrScUKgpBRIndPPg8pHB
"""

def text_join(*args):

    total_art = list()
    total_unique = list()
    test_unique = list()
    for arg in args:
        file = open(arg, "r")
        content = file.read().replace("{{", "{").replace("}}", "}").replace(" = ", "=")
        content = content.split("\n\n")
        total_art = total_art + content

    total_art = list(set(total_art))
    
    for item in total_art:
        try:
            titulo = item.split("\nTitle")[1][5:10]
        except:
            titulo = item.split("\ntitle")[1][5:10]
            
        if titulo not in test_unique:
            test_unique.append(titulo)
            total_unique.append(item)
               
    content_format = "\n\n".join(total_unique)
    
    new_file= open("/content/drive/MyDrive/Colab Notebooks/artigos.bib", "w")
    new_file.write(content_format)
    new_file.close()